# Generated by Django 3.1 on 2020-08-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='isbn',
        ),
    ]
