# Generated by Django 3.1.3 on 2020-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0005_auto_20200828_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
