# Generated by Django 3.1.3 on 2020-11-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0006_auto_20201106_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='ebook',
            field=models.FileField(upload_to='media/ebooks/'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='image',
            field=models.FileField(upload_to='media/images/'),
        ),
    ]
